package report

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/iam-orsu/ciotx/cli/pkg/types"
)

// ScanStats contains metrics for the report header.
type ScanStats struct {
	TotalFiles             int
	TotalLines             int
	HallucinationsDropped  int
	FalsePositivesFiltered int
	DurationSeconds        float64
	EstimatedCostUSD       float64
}

// WriteJSON saves findings to a JSON file.
func WriteJSON(findings []*types.Finding, outputPath string) error {
	data, err := json.MarshalIndent(findings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(outputPath, data, 0o644)
}

type rgb struct{ r, g, b int }

var (
	colCrit    = rgb{248, 81, 73}
	colHigh    = rgb{240, 136, 62}
	colMed     = rgb{210, 153, 34}
	colLow     = rgb{63, 185, 80}
	colHeader  = rgb{13, 17, 23}
	colAccent  = rgb{88, 166, 255}
	colText    = rgb{30, 30, 30}
	colMuted   = rgb{100, 110, 120}
	colLightBg = rgb{245, 247, 250}
	colCodeBg  = rgb{238, 240, 244}
	colWhite   = rgb{255, 255, 255}
	colBorder  = rgb{210, 215, 220}
)

func sevColor(severity string) rgb {
	switch severity {
	case "Critical":
		return colCrit
	case "High":
		return colHigh
	case "Medium":
		return colMed
	default:
		return colLow
	}
}

func setFill(pdf *fpdf.Fpdf, c rgb) {
	pdf.SetFillColor(c.r, c.g, c.b)
}

func setDraw(pdf *fpdf.Fpdf, c rgb) {
	pdf.SetDrawColor(c.r, c.g, c.b)
}

func setColor(pdf *fpdf.Fpdf, c rgb) {
	pdf.SetTextColor(c.r, c.g, c.b)
}

// WritePDF generates a styled PDF security report.
func WritePDF(findings []*types.Finding, stats *ScanStats, targetDir, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AliasNbPages("{nb}")
	pdf.SetAutoPageBreak(true, 20)
	pdf.SetMargins(15, 15, 15)

	// Footer on every page.
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "", 8)
		setColor(pdf, colMuted)
		pdf.CellFormat(0, 5, fmt.Sprintf("Generated by ciotx  |  Page %d of {nb}", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	pdf.AddPage()

	pw, _ := pdf.GetPageSize()
	margin := 15.0
	cw := pw - 2*margin // content width: 180mm

	// ── Header bar ───────────────────────────────────────────────────
	setFill(pdf, colHeader)
	pdf.Rect(0, 0, pw, 32, "F")

	pdf.SetXY(margin, 7)
	pdf.SetFont("Helvetica", "B", 24)
	setColor(pdf, colAccent)
	pdf.Cell(22, 10, "ciotx")

	setColor(pdf, colWhite)
	pdf.SetFont("Helvetica", "", 24)
	pdf.Cell(60, 10, " Security Report")

	pdf.SetXY(margin, 21)
	pdf.SetFont("Helvetica", "", 8.5)
	setColor(pdf, colMuted)
	meta := fmt.Sprintf("Target: %s   |   Generated: %s   |   Duration: %.1fs",
		targetDir,
		time.Now().Format("2006-01-02 15:04"),
		stats.DurationSeconds,
	)
	pdf.Cell(cw, 5, meta)

	pdf.SetY(40)

	// ── Severity summary boxes ────────────────────────────────────────
	counts := map[string]int{"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
	for _, f := range findings {
		counts[f.Severity]++
	}

	type sevBox struct {
		label string
		col   rgb
		key   string
	}
	boxes := []sevBox{
		{"CRITICAL", colCrit, "Critical"},
		{"HIGH", colHigh, "High"},
		{"MEDIUM", colMed, "Medium"},
		{"LOW", colLow, "Low"},
	}

	boxGap := 4.0
	boxW := (cw - float64(len(boxes)-1)*boxGap) / float64(len(boxes)) // ~41mm
	boxH := 24.0
	startY := pdf.GetY()

	for i, b := range boxes {
		x := margin + float64(i)*(boxW+boxGap)
		// Colored background
		setFill(pdf, b.col)
		pdf.RoundedRect(x, startY, boxW, boxH, 3, "1234", "F")
		// Count
		pdf.SetFont("Helvetica", "B", 22)
		setColor(pdf, colWhite)
		pdf.SetXY(x, startY+3)
		pdf.CellFormat(boxW, 10, fmt.Sprintf("%d", counts[b.key]), "", 0, "C", false, 0, "")
		// Label
		pdf.SetFont("Helvetica", "B", 7.5)
		pdf.SetXY(x, startY+14)
		pdf.CellFormat(boxW, 5, b.label, "", 0, "C", false, 0, "")
	}

	pdf.SetY(startY + boxH + 6)

	// ── Stats bar ────────────────────────────────────────────────────
	statsY := pdf.GetY()
	setFill(pdf, colLightBg)
	setDraw(pdf, colBorder)
	pdf.RoundedRect(margin, statsY, cw, 12, 2, "1234", "FD")

	statItems := []string{
		fmt.Sprintf("Files Scanned: %d", stats.TotalFiles),
		fmt.Sprintf("Lines Analyzed: %s", formatNumber(stats.TotalLines)),
		fmt.Sprintf("Noise Filtered: %d", stats.HallucinationsDropped+stats.FalsePositivesFiltered),
		fmt.Sprintf("Total Findings: %d", len(findings)),
	}
	colW := cw / float64(len(statItems))
	pdf.SetFont("Helvetica", "", 9)
	setColor(pdf, colText)
	for i, s := range statItems {
		pdf.SetXY(margin+float64(i)*colW, statsY+4)
		pdf.CellFormat(colW, 5, s, "", 0, "C", false, 0, "")
	}

	pdf.SetY(statsY + 18)

	// ── Section title ────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 13)
	setColor(pdf, colText)
	pdf.SetX(margin) // reset X — stats bar CellFormat loop leaves X at the right edge
	pdf.Cell(cw, 7, "Security Findings")
	pdf.Ln(8)

	setDraw(pdf, colBorder)
	pdf.Line(margin, pdf.GetY(), margin+cw, pdf.GetY())
	pdf.Ln(5)

	// ── Sort findings: Critical → High → Medium → Low ─────────────────
	sorted := make([]*types.Finding, len(findings))
	copy(sorted, findings)
	sevOrder := map[string]int{"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
	sort.Slice(sorted, func(i, j int) bool {
		return sevOrder[sorted[i].Severity] < sevOrder[sorted[j].Severity]
	})

	if len(sorted) == 0 {
		// Empty state
		pdf.Ln(10)
		pdf.SetFont("Helvetica", "B", 14)
		setColor(pdf, colLow)
		pdf.CellFormat(cw, 10, "No Vulnerabilities Found", "", 1, "C", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		setColor(pdf, colMuted)
		pdf.CellFormat(cw, 7, "The codebase passed all security checks in this scan.", "", 1, "C", false, 0, "")
	}

	for i, f := range sorted {
		drawFinding(pdf, f, i+1, margin, cw)
	}

	return pdf.OutputFileAndClose(outputPath)
}

// drawFinding renders one finding card onto the PDF.
func drawFinding(pdf *fpdf.Fpdf, f *types.Finding, num int, margin, cw float64) {
	sc := sevColor(f.Severity)

	// Estimate content height to decide page break.
	descLines := estimateLines(f.Description, cw-20, 9)
	evidLines := estimateLines(f.Evidence, cw-20, 8.5)
	remLines := estimateLines(f.Remediation, cw-20, 8.5)
	estHeight := 14.0 + float64(descLines)*4.5 + float64(evidLines)*4.5 + float64(remLines)*4.5 + 30
	if pdf.GetY()+estHeight > 270 {
		pdf.AddPage()
	}

	cardY := pdf.GetY()

	// Card header background (top corners rounded, bottom corners square).
	// The left 3mm column is reserved for the severity accent bar drawn at the end.
	setFill(pdf, rgb{252, 253, 254})
	setDraw(pdf, colBorder)
	cardX := margin + 3
	cardInnerW := cw - 3
	pdf.RoundedRectExt(cardX, cardY, cardInnerW, 10, 2, 2, 0, 0, "FD") // rTL=2 rTR=2 rBR=0 rBL=0

	// ── Finding header row ───────────────────────────────────────────
	headerH := 9.0

	// Severity badge
	badgeW := 18.0
	pdf.SetXY(cardX+4, cardY+2)
	setFill(pdf, sc)
	pdf.RoundedRect(cardX+3, cardY+2, badgeW, 5, 1.5, "1234", "F")
	pdf.SetFont("Helvetica", "B", 7)
	setColor(pdf, colWhite)
	pdf.SetXY(cardX+3, cardY+2.5)
	pdf.CellFormat(badgeW, 4.5, strings.ToUpper(f.Severity), "", 0, "C", false, 0, "")

	// Title
	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, colText)
	pdf.SetXY(cardX+3+badgeW+3, cardY+2.5)
	titleText := fmt.Sprintf("#%d: %s", num, f.Title)
	pdf.CellFormat(cardInnerW-badgeW-15, headerH-2, titleText, "", 0, "L", false, 0, "")

	// File + lines (right-aligned)
	pdf.SetFont("Helvetica", "", 8)
	setColor(pdf, colMuted)
	fileText := fmt.Sprintf("%s  L%d-%d", f.File, f.LineStart, f.LineEnd)
	pdf.SetXY(cardX+3, cardY+2.5)
	pdf.CellFormat(cardInnerW-6, headerH-2, fileText, "", 0, "R", false, 0, "")

	pdf.SetY(cardY + headerH + 1)

	// Divider
	setDraw(pdf, colBorder)
	pdf.Line(cardX+3, pdf.GetY(), cardX+cardInnerW-3, pdf.GetY())
	pdf.Ln(3)

	// ── Body ─────────────────────────────────────────────────────────
	bodyX := cardX + 5
	bodyW := cardInnerW - 10

	// CWE chip
	if f.CWE != "" {
		setFill(pdf, colLightBg)
		pdf.SetFont("Helvetica", "", 7.5)
		setColor(pdf, colMuted)
		chipW := float64(len(f.CWE))*2.0 + 8
		pdf.RoundedRect(bodyX, pdf.GetY(), chipW, 4.5, 1, "1234", "F")
		pdf.SetXY(bodyX, pdf.GetY())
		pdf.CellFormat(chipW, 4.5, f.CWE, "", 0, "C", false, 0, "")
		pdf.Ln(6)
	}

	// Description
	if f.Description != "" {
		pdf.SetFont("Helvetica", "B", 8)
		setColor(pdf, colMuted)
		pdf.SetX(bodyX)
		pdf.Cell(bodyW, 4.5, "DESCRIPTION")
		pdf.Ln(4.5)
		pdf.SetFont("Helvetica", "", 9)
		setColor(pdf, colText)
		pdf.SetX(bodyX)
		pdf.MultiCell(bodyW, 4.5, f.Description, "", "L", false)
		pdf.Ln(2)
	}

	// Evidence code block
	if f.Evidence != "" {
		pdf.SetFont("Helvetica", "B", 8)
		setColor(pdf, colMuted)
		pdf.SetX(bodyX)
		pdf.Cell(bodyW, 4.5, "VULNERABLE CODE")
		pdf.Ln(5)

		codeY := pdf.GetY()
		codeLines := strings.Split(f.Evidence, "\n")
		codeH := float64(len(codeLines))*4.0 + 4
		if codeH < 8 {
			codeH = 8
		}
		setFill(pdf, colCodeBg)
		setDraw(pdf, colBorder)
		pdf.RoundedRect(bodyX, codeY, bodyW, codeH, 2, "1234", "FD")
		pdf.SetFont("Courier", "", 7.5)
		setColor(pdf, rgb{180, 50, 50})
		for j, line := range codeLines {
			pdf.SetXY(bodyX+3, codeY+2+float64(j)*4.0)
			pdf.CellFormat(bodyW-6, 4.0, line, "", 0, "L", false, 0, "")
		}
		pdf.SetY(codeY + codeH + 3)
	}

	// Remediation
	if f.Remediation != "" {
		pdf.SetFont("Helvetica", "B", 8)
		setColor(pdf, colMuted)
		pdf.SetX(bodyX)
		pdf.Cell(bodyW, 4.5, "HOW TO FIX")
		pdf.Ln(5)

		remY := pdf.GetY()
		remLines := strings.Split(f.Remediation, "\n")
		remH := float64(len(remLines))*4.0 + 4
		if remH < 8 {
			remH = 8
		}
		setFill(pdf, rgb{240, 250, 242})
		setDraw(pdf, rgb{180, 220, 185})
		pdf.RoundedRect(bodyX, remY, bodyW, remH, 2, "1234", "FD")
		pdf.SetFont("Helvetica", "", 8)
		setColor(pdf, rgb{30, 100, 40})
		for j, line := range remLines {
			pdf.SetXY(bodyX+3, remY+2+float64(j)*4.0)
			pdf.CellFormat(bodyW-6, 4.0, line, "", 0, "L", false, 0, "")
		}
		pdf.SetY(remY + remH + 3)
	}

	pdf.Ln(3)

	// Draw the left accent bar now that we know the card's full height.
	// Guard against negative height if a page break occurred mid-card.
	cardEndY := pdf.GetY()
	cardH := cardEndY - cardY
	if cardH > 0 {
		setFill(pdf, sc)
		pdf.Rect(margin, cardY, 3, cardH, "F")
	}

	pdf.Ln(4) // gap between cards
}

func estimateLines(text string, widthMM, fontSize float64) int {
	if text == "" {
		return 0
	}
	// Rough estimate: ~1.8 chars per mm at typical font sizes
	charsPerLine := int(widthMM * 1.8 / (fontSize / 10))
	if charsPerLine < 1 {
		charsPerLine = 1
	}
	lines := 0
	for _, para := range strings.Split(text, "\n") {
		lines += (len(para) / charsPerLine) + 1
	}
	return lines
}

func formatNumber(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	result := make([]byte, 0, len(s)+(len(s)-1)/3)
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			result = append(result, ',')
		}
		result = append(result, byte(c))
	}
	return string(result)
}
