package report

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/iam-orsu/ciotx/cli/pkg/types"
)

// ScanStats contains metrics for the report header.
type ScanStats struct {
	TotalFiles             int
	TotalLines             int
	HallucinationsDropped  int
	FalsePositivesFiltered int
	DurationSeconds        float64
	EstimatedCostUSD       float64
}

// WriteJSON saves findings to a JSON file.
func WriteJSON(findings []*types.Finding, outputPath string) error {
	data, err := json.MarshalIndent(findings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(outputPath, data, 0o644)
}

// ── Colour palette ────────────────────────────────────────────────────────────

type rgb struct{ r, g, b int }

var (
	colCrit   = rgb{214, 40, 40}
	colHigh   = rgb{217, 102, 15}
	colMed    = rgb{176, 126, 0}
	colLow    = rgb{34, 139, 68}
	colHeader = rgb{15, 20, 30}
	colText   = rgb{20, 20, 30}
	colMuted  = rgb{105, 112, 125}
	colBorder = rgb{210, 213, 220}
	colRowAlt = rgb{247, 248, 251}
	colWhite  = rgb{255, 255, 255}
)

func sevColor(s string) rgb {
	switch s {
	case "Critical":
		return colCrit
	case "High":
		return colHigh
	case "Medium":
		return colMed
	default:
		return colLow
	}
}

func fc(pdf *fpdf.Fpdf, c rgb) { pdf.SetFillColor(c.r, c.g, c.b) }
func dc(pdf *fpdf.Fpdf, c rgb) { pdf.SetDrawColor(c.r, c.g, c.b) }
func tc(pdf *fpdf.Fpdf, c rgb) { pdf.SetTextColor(c.r, c.g, c.b) }

// ── Layout constants ──────────────────────────────────────────────────────────

const (
	pgW     = 210.0
	mgL     = 20.0
	mgR     = 20.0
	mgT     = 20.0 // top margin (pages 2+); header drawn in 0-18mm
	mgB     = 22.0
	cW      = pgW - mgL - mgR // 170 mm content width
	lh      = 5.2             // default line height for body text
)

// ── Public entry point ────────────────────────────────────────────────────────

// WritePDF generates a professional compliance-grade PDF security report.
func WritePDF(findings []*types.Finding, stats *ScanStats, targetDir, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AliasNbPages("{nb}")
	pdf.SetMargins(mgL, mgT, mgR)
	pdf.SetAutoPageBreak(true, mgB)

	// Running header on every page except the cover.
	pdf.SetHeaderFunc(func() {
		if pdf.PageNo() == 1 {
			return
		}
		pdf.SetFont("Helvetica", "", 7)
		tc(pdf, colMuted)
		pdf.SetXY(mgL, 8)
		pdf.CellFormat(cW/2, 4, "SECURITY ASSESSMENT REPORT", "", 0, "L", false, 0, "")
		pdf.CellFormat(cW/2, 4, "CONFIDENTIAL", "", 0, "R", false, 0, "")
		dc(pdf, colBorder)
		pdf.SetLineWidth(0.2)
		pdf.Line(mgL, 13.5, mgL+cW, 13.5)
	})

	// Footer on every page except the cover.
	pdf.SetFooterFunc(func() {
		if pdf.PageNo() == 1 {
			return
		}
		pdf.SetY(-14)
		dc(pdf, colBorder)
		pdf.SetLineWidth(0.2)
		pdf.Line(mgL, pdf.GetY(), mgL+cW, pdf.GetY())
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "", 7.5)
		tc(pdf, colMuted)
		pdf.SetX(mgL)
		pdf.CellFormat(cW/2, 5,
			fmt.Sprintf("Generated by ciotx  |  %s", time.Now().Format("2006-01-02")),
			"", 0, "L", false, 0, "")
		pdf.CellFormat(cW/2, 5,
			fmt.Sprintf("Page %d of {nb}", pdf.PageNo()),
			"", 0, "R", false, 0, "")
	})

	counts := countSeverities(findings)

	// ── Cover page ────────────────────────────────────────────────────
	pdf.AddPage()
	pdf.SetAutoPageBreak(false, 0) // cover is fixed-layout; never auto-break mid-cover
	drawCover(pdf, findings, stats, targetDir, counts)
	pdf.SetAutoPageBreak(true, mgB) // re-enable for content pages

	// ── Executive summary ─────────────────────────────────────────────
	pdf.AddPage()
	drawSummary(pdf, findings, stats, targetDir, counts)

	// ── Detailed findings ─────────────────────────────────────────────
	sorted := sortedFindings(findings)
	if len(sorted) > 0 {
		pdf.AddPage()
		sectionTitle(pdf, "Detailed Findings")
		for i, f := range sorted {
			drawFinding(pdf, f, i+1)
		}
	}

	return pdf.OutputFileAndClose(outputPath)
}

// ── Cover page ────────────────────────────────────────────────────────────────

func drawCover(pdf *fpdf.Fpdf, findings []*types.Finding, stats *ScanStats, targetDir string, counts map[string]int) {
	// Dark banner
	fc(pdf, colHeader)
	pdf.Rect(0, 0, pgW, 80, "F")

	// Product name
	pdf.SetFont("Helvetica", "B", 34)
	tc(pdf, rgb{80, 150, 255})
	pdf.SetXY(mgL, 18)
	pdf.Cell(60, 14, "ciotx")

	// Report type
	pdf.SetFont("Helvetica", "B", 16)
	tc(pdf, colWhite)
	pdf.SetXY(mgL, 38)
	pdf.Cell(cW, 8, "SECURITY ASSESSMENT REPORT")

	// Sub-label
	pdf.SetFont("Helvetica", "", 9)
	tc(pdf, rgb{110, 125, 145})
	pdf.SetXY(mgL, 52)
	pdf.Cell(cW, 5, "CONFIDENTIAL  |  RESTRICTED DISTRIBUTION")

	// Date (right-aligned in banner)
	pdf.SetFont("Helvetica", "", 9)
	tc(pdf, rgb{110, 125, 145})
	pdf.SetXY(mgL, 64)
	pdf.CellFormat(cW, 5, time.Now().Format("January 02, 2006"), "", 0, "R", false, 0, "")

	// ── Target metadata block ─────────────────────────────────────────
	rows := [][2]string{
		{"Target", targetDir},
		{"Scan Date", time.Now().Format("2006-01-02 15:04 UTC")},
		{"Duration", fmt.Sprintf("%.1f seconds", stats.DurationSeconds)},
		{"Files Scanned", fmt.Sprintf("%d files  |  %s lines", stats.TotalFiles, formatNumber(stats.TotalLines))},
	}
	y := 96.0
	for _, row := range rows {
		pdf.SetFont("Helvetica", "B", 9)
		tc(pdf, colMuted)
		pdf.SetXY(mgL, y)
		pdf.CellFormat(32, lh, row[0]+":", "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9.5)
		tc(pdf, colText)
		pdf.CellFormat(cW-32, lh, row[1], "", 0, "L", false, 0, "")
		y += 9
	}

	// Divider
	dc(pdf, colBorder)
	pdf.SetLineWidth(0.3)
	pdf.Line(mgL, y+4, mgL+cW, y+4)
	y += 12

	// ── Findings summary table ────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 10)
	tc(pdf, colText)
	pdf.SetXY(mgL, y)
	pdf.Cell(cW, 6, "FINDINGS SUMMARY")
	y += 10

	sevRows := []struct {
		label string
		col   rgb
		key   string
	}{
		{"Critical", colCrit, "Critical"},
		{"High", colHigh, "High"},
		{"Medium", colMed, "Medium"},
		{"Low", colLow, "Low"},
	}

	for i, sr := range sevRows {
		rowY := y + float64(i)*11
		// Alternate row background
		if i%2 == 0 {
			fc(pdf, colRowAlt)
			pdf.Rect(mgL, rowY, cW, 10, "F")
		}
		// Severity colour bar on left
		fc(pdf, sr.col)
		pdf.Rect(mgL, rowY, 3, 10, "F")
		// Label
		pdf.SetFont("Helvetica", "B", 10)
		tc(pdf, sr.col)
		pdf.SetXY(mgL+7, rowY+3)
		pdf.CellFormat(50, 4.5, strings.ToUpper(sr.label), "", 0, "L", false, 0, "")
		// Count (large)
		pdf.SetFont("Helvetica", "B", 13)
		tc(pdf, colText)
		pdf.CellFormat(20, 4.5, fmt.Sprintf("%d", counts[sr.key]), "", 0, "L", false, 0, "")
		// Risk bar proportional fill
		if len(findings) > 0 {
			barMaxW := 60.0
			barW := barMaxW * float64(counts[sr.key]) / float64(len(findings))
			barX := mgL + cW - barMaxW - 5
			fc(pdf, colBorder)
			pdf.Rect(barX, rowY+3.5, barMaxW, 3, "F")
			if barW > 0 {
				fc(pdf, sr.col)
				pdf.Rect(barX, rowY+3.5, barW, 3, "F")
			}
		}
	}

	// Total row
	totalY := y + float64(len(sevRows))*11 + 2
	dc(pdf, colBorder)
	pdf.SetLineWidth(0.2)
	pdf.Line(mgL, totalY, mgL+cW, totalY)
	pdf.SetFont("Helvetica", "B", 10)
	tc(pdf, colText)
	pdf.SetXY(mgL+7, totalY+3)
	pdf.CellFormat(50, 5, "TOTAL FINDINGS", "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(20, 5, fmt.Sprintf("%d", len(findings)), "", 0, "L", false, 0, "")

	// ── Confidentiality notice ────────────────────────────────────────
	noticeY := 262.0
	fc(pdf, rgb{244, 245, 248})
	pdf.Rect(0, noticeY, pgW, 35, "F")
	pdf.SetFont("Helvetica", "B", 7.5)
	tc(pdf, colMuted)
	pdf.SetXY(mgL, noticeY+6)
	pdf.Cell(cW, 4, "CONFIDENTIALITY NOTICE")
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(mgL, noticeY+11)
	pdf.MultiCell(cW, 4.2,
		"This document contains sensitive security findings and is intended solely for "+
			"the organization that commissioned this assessment. Distribution, reproduction, "+
			"or disclosure to unauthorized parties is strictly prohibited.",
		"", "L", false)
}

// ── Executive summary ─────────────────────────────────────────────────────────

func drawSummary(pdf *fpdf.Fpdf, findings []*types.Finding, stats *ScanStats, targetDir string, counts map[string]int) {
	sectionTitle(pdf, "Executive Summary")

	// Narrative paragraph
	riskLabel := riskRating(counts)
	var narrative string
	if len(findings) == 0 {
		narrative = fmt.Sprintf(
			"The automated security assessment of %s completed successfully. No security vulnerabilities "+
				"were identified. The codebase passed all applied security checks.",
			targetDir)
	} else {
		narrative = fmt.Sprintf(
			"The automated security assessment of %s identified %d security finding(s) across %d file(s) "+
				"and %s lines of source code. The overall risk rating is %s. "+
				"Critical and High severity findings require immediate remediation before deployment.",
			targetDir, len(findings), stats.TotalFiles, formatNumber(stats.TotalLines), riskLabel)
	}
	pdf.SetFont("Helvetica", "", 10)
	tc(pdf, colText)
	pdf.SetX(mgL)
	pdf.MultiCell(cW, lh, narrative, "", "L", false)
	pdf.Ln(6)

	// ── Risk rating boxes ─────────────────────────────────────────────
	sevs := []struct {
		label string
		col   rgb
		key   string
	}{
		{"CRITICAL", colCrit, "Critical"},
		{"HIGH", colHigh, "High"},
		{"MEDIUM", colMed, "Medium"},
		{"LOW", colLow, "Low"},
	}

	boxW := (cW - 3*4) / 4
	boxH := 22.0
	startY := pdf.GetY()

	for i, s := range sevs {
		x := mgL + float64(i)*(boxW+4)
		// Border
		dc(pdf, s.col)
		pdf.SetLineWidth(0.5)
		pdf.Rect(x, startY, boxW, boxH, "D")
		// Top accent bar
		fc(pdf, s.col)
		pdf.Rect(x, startY, boxW, 2.5, "F")
		// Count
		pdf.SetFont("Helvetica", "B", 20)
		tc(pdf, s.col)
		pdf.SetXY(x, startY+3.5)
		pdf.CellFormat(boxW, 10, fmt.Sprintf("%d", counts[s.key]), "", 0, "C", false, 0, "")
		// Label
		pdf.SetFont("Helvetica", "B", 7)
		tc(pdf, colMuted)
		pdf.SetXY(x, startY+14)
		pdf.CellFormat(boxW, 5, s.label, "", 0, "C", false, 0, "")
	}
	pdf.SetY(startY + boxH + 8)

	// ── Assessment metrics table ──────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 10)
	tc(pdf, colText)
	pdf.SetX(mgL)
	pdf.Cell(cW, 6, "Assessment Metrics")
	pdf.Ln(7)

	tableRows := [][]string{
		{"Files Scanned", fmt.Sprintf("%d", stats.TotalFiles)},
		{"Lines Analyzed", formatNumber(stats.TotalLines)},
		{"Scan Duration", fmt.Sprintf("%.1f seconds", stats.DurationSeconds)},
		{"Noise Filtered", fmt.Sprintf("%d (hallucinations and false positives removed)", stats.HallucinationsDropped+stats.FalsePositivesFiltered)},
		{"Total Findings", fmt.Sprintf("%d", len(findings))},
		{"Overall Risk", riskLabel},
	}
	labelColW := 45.0
	rowH := 7.5
	pdf.SetLineWidth(0.1)
	for i, row := range tableRows {
		ry := pdf.GetY()
		if i%2 == 0 {
			fc(pdf, colRowAlt)
			pdf.Rect(mgL, ry, cW, rowH, "F")
		}
		dc(pdf, colBorder)
		pdf.Rect(mgL, ry, cW, rowH, "D")
		pdf.SetFont("Helvetica", "B", 9)
		tc(pdf, colMuted)
		pdf.SetXY(mgL+3, ry+1.8)
		pdf.CellFormat(labelColW, rowH-3, row[0], "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9.5)
		tc(pdf, colText)
		pdf.CellFormat(cW-labelColW-3, rowH-3, row[1], "", 1, "L", false, 0, "")
	}

	// ── Findings by severity breakdown ────────────────────────────────
	if len(findings) > 0 {
		pdf.Ln(8)
		pdf.SetFont("Helvetica", "B", 10)
		tc(pdf, colText)
		pdf.SetX(mgL)
		pdf.Cell(cW, 6, "Findings by Severity")
		pdf.Ln(7)

		colLabel := 40.0
		colCount := 20.0
		colBar := cW - colLabel - colCount
		maxCount := 0
		for _, sr := range sevs {
			if counts[sr.key] > maxCount {
				maxCount = counts[sr.key]
			}
		}
		rowH = 8.0
		for i, sr := range sevs {
			ry := pdf.GetY()
			if i%2 == 0 {
				fc(pdf, colRowAlt)
				pdf.Rect(mgL, ry, cW, rowH, "F")
			}
			fc(pdf, sr.col)
			pdf.Rect(mgL, ry, 3, rowH, "F")
			pdf.SetFont("Helvetica", "B", 9)
			tc(pdf, colText)
			pdf.SetXY(mgL+6, ry+2)
			pdf.CellFormat(colLabel, rowH-4, sr.label, "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "B", 9)
			pdf.CellFormat(colCount, rowH-4, fmt.Sprintf("%d", counts[sr.key]), "", 0, "C", false, 0, "")
			if maxCount > 0 {
				barW := colBar * float64(counts[sr.key]) / float64(maxCount)
				fc(pdf, colBorder)
				pdf.Rect(mgL+colLabel+colCount, ry+3, colBar-4, 2.5, "F")
				if barW > 0 {
					fc(pdf, sr.col)
					pdf.Rect(mgL+colLabel+colCount, ry+3, barW-4, 2.5, "F")
				}
			}
			pdf.Ln(rowH)
		}
	}
}

// ── Individual finding ────────────────────────────────────────────────────────

func drawFinding(pdf *fpdf.Fpdf, f *types.Finding, num int) {
	sc := sevColor(f.Severity)

	// Reserve enough room for header + metadata + at least one line of content.
	// If not enough room, start a new page.
	if pdf.GetY() > 297-mgB-38 {
		pdf.AddPage()
	}

	// ── Header band ───────────────────────────────────────────────────
	headerY := pdf.GetY()
	headerH := 11.0
	fc(pdf, sc)
	pdf.Rect(mgL, headerY, cW, headerH, "F")

	// Finding number + severity
	pdf.SetFont("Helvetica", "B", 8.5)
	tc(pdf, rgb{255, 255, 255})
	pdf.SetXY(mgL+3, headerY+3)
	badge := fmt.Sprintf("  #%d   %s  ", num, strings.ToUpper(f.Severity))
	badgeW := pdf.GetStringWidth(badge) + 2
	pdf.CellFormat(badgeW, 5, badge, "", 0, "L", false, 0, "")

	// Title — truncate if too long to fit on one line
	pdf.SetFont("Helvetica", "B", 9.5)
	tc(pdf, colWhite)
	titleX := mgL + 3 + badgeW + 2
	titleW := cW - (titleX - mgL) - 3
	title := f.Title
	for pdf.GetStringWidth(title) > titleW && len(title) > 10 {
		title = title[:len(title)-4] + "..."
	}
	pdf.SetXY(titleX, headerY+3)
	pdf.CellFormat(titleW, 5, title, "", 0, "L", false, 0, "")

	pdf.SetY(headerY + headerH)

	// ── Metadata bar ──────────────────────────────────────────────────
	metaH := 9.0
	fc(pdf, rgb{247, 248, 251})
	dc(pdf, colBorder)
	pdf.SetLineWidth(0.15)
	pdf.Rect(mgL, pdf.GetY(), cW, metaH, "FD")

	metaY := pdf.GetY() + 2.5
	colW3 := cW / 3

	metaItems := []struct{ label, value string }{
		{"FILE", shortenPath(f.File, 30)},
		{"LINES", fmt.Sprintf("%d - %d", f.LineStart, f.LineEnd)},
		{"CWE", shortenStr(f.CWE, 28)},
	}
	for i, m := range metaItems {
		x := mgL + float64(i)*colW3
		pdf.SetFont("Helvetica", "B", 7)
		tc(pdf, colMuted)
		pdf.SetXY(x+3, metaY)
		pdf.CellFormat(14, 4, m.label+":", "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 8.5)
		tc(pdf, colText)
		pdf.CellFormat(colW3-17, 4, m.value, "", 0, "L", false, 0, "")
	}
	pdf.SetY(pdf.GetY() + metaH)

	// ── Body content ──────────────────────────────────────────────────
	bodyX := mgL + 4
	bodyW := cW - 8
	pdf.Ln(3)

	// Description
	if f.Description != "" {
		fieldLabel(pdf, bodyX, bodyW, "DESCRIPTION")
		pdf.SetFont("Helvetica", "", 9.5)
		tc(pdf, colText)
		pdf.SetX(bodyX)
		pdf.MultiCell(bodyW, lh, f.Description, "", "L", false)
		pdf.Ln(3)
	}

	// Evidence code block — draw background rect BEFORE MultiCell using exact line count
	if f.Evidence != "" {
		fieldLabel(pdf, bodyX, bodyW, "VULNERABLE CODE")
		code := prepareCode(f.Evidence, 90)
		lineCount := len(strings.Split(code, "\n"))
		blockH := float64(lineCount)*4.3 + 5
		// If block doesn't fit, push to next page
		if pdf.GetY()+blockH > 297-mgB {
			pdf.AddPage()
			fieldLabel(pdf, bodyX, bodyW, "VULNERABLE CODE (continued)")
		}
		blockY := pdf.GetY()
		fc(pdf, rgb{250, 246, 245})
		dc(pdf, rgb{220, 195, 195})
		pdf.SetLineWidth(0.3)
		pdf.Rect(bodyX, blockY, bodyW, blockH, "FD")
		pdf.SetFont("Courier", "", 8)
		tc(pdf, rgb{180, 40, 40})
		pdf.SetXY(bodyX+3, blockY+2.5)
		pdf.MultiCell(bodyW-6, 4.3, code, "", "L", false)
		pdf.SetY(blockY + blockH + 3)
	}

	// Remediation — same exact-height approach
	if f.Remediation != "" {
		fieldLabel(pdf, bodyX, bodyW, "HOW TO FIX")
		rem := prepareText(f.Remediation)
		lineCount := estimateTextLines(rem, bodyW-6, 9.5)
		blockH := float64(lineCount)*lh + 5
		if pdf.GetY()+blockH > 297-mgB {
			pdf.AddPage()
			fieldLabel(pdf, bodyX, bodyW, "HOW TO FIX (continued)")
		}
		blockY := pdf.GetY()
		fc(pdf, rgb{242, 250, 244})
		dc(pdf, rgb{180, 220, 185})
		pdf.SetLineWidth(0.3)
		pdf.Rect(bodyX, blockY, bodyW, blockH, "FD")
		pdf.SetFont("Helvetica", "", 9.5)
		tc(pdf, rgb{25, 95, 40})
		pdf.SetXY(bodyX+3, blockY+2.5)
		pdf.MultiCell(bodyW-6, lh, rem, "", "L", false)
		pdf.SetY(blockY + blockH + 3)
	}

	// Bottom rule between findings
	pdf.Ln(2)
	dc(pdf, colBorder)
	pdf.SetLineWidth(0.15)
	pdf.Line(mgL, pdf.GetY(), mgL+cW, pdf.GetY())
	pdf.Ln(7)
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func sectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 15)
	tc(pdf, colText)
	pdf.SetX(mgL)
	pdf.Cell(cW, 8, title)
	pdf.Ln(9)
	dc(pdf, colBorder)
	pdf.SetLineWidth(0.3)
	pdf.Line(mgL, pdf.GetY(), mgL+cW, pdf.GetY())
	pdf.Ln(7)
}

func fieldLabel(pdf *fpdf.Fpdf, x, w float64, label string) {
	pdf.SetFont("Helvetica", "B", 7.5)
	tc(pdf, colMuted)
	pdf.SetX(x)
	pdf.Cell(w, 4, label)
	pdf.Ln(4.8)
}

// prepareCode truncates lines longer than maxChars and strips trailing whitespace.
func prepareCode(code string, maxChars int) string {
	lines := strings.Split(code, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimRight(line, " \t")
		if len(line) > maxChars {
			line = line[:maxChars-3] + "..."
		}
		out = append(out, line)
	}
	// Remove trailing blank lines
	for len(out) > 0 && out[len(out)-1] == "" {
		out = out[:len(out)-1]
	}
	return strings.Join(out, "\n")
}

// prepareText strips trailing whitespace from each line.
func prepareText(text string) string {
	lines := strings.Split(text, "\n")
	out := make([]string, 0, len(lines))
	for _, l := range lines {
		out = append(out, strings.TrimRight(l, " \t"))
	}
	return strings.Join(out, "\n")
}

// estimateTextLines estimates how many lines MultiCell will produce.
// At 9.5pt Helvetica each char is ~2.1mm wide, so ~0.48 chars fit per mm.
func estimateTextLines(text string, widthMM, _ float64) int {
	const charsPerMM = 0.48
	limit := int(widthMM * charsPerMM)
	if limit < 10 {
		limit = 10
	}
	total := 0
	for _, para := range strings.Split(text, "\n") {
		if len(para) == 0 {
			total++
			continue
		}
		total += (len(para) + limit - 1) / limit
	}
	if total == 0 {
		return 1
	}
	return total
}

func shortenPath(path string, max int) string {
	if len(path) <= max {
		return path
	}
	return "..." + path[len(path)-(max-3):]
}

func shortenStr(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-3] + "..."
}

func countSeverities(findings []*types.Finding) map[string]int {
	c := map[string]int{"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
	for _, f := range findings {
		c[f.Severity]++
	}
	return c
}

func riskRating(counts map[string]int) string {
	switch {
	case counts["Critical"] > 0:
		return "CRITICAL"
	case counts["High"] > 0:
		return "HIGH"
	case counts["Medium"] > 0:
		return "MEDIUM"
	default:
		return "LOW"
	}
}

func sortedFindings(findings []*types.Finding) []*types.Finding {
	order := map[string]int{"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
	out := make([]*types.Finding, len(findings))
	copy(out, findings)
	sort.Slice(out, func(i, j int) bool {
		return order[out[i].Severity] < order[out[j].Severity]
	})
	return out
}

func formatNumber(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	result := make([]byte, 0, len(s)+(len(s)-1)/3)
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			result = append(result, ',')
		}
		result = append(result, byte(c))
	}
	return string(result)
}
