#!/bin/bash
# =======================================================================
#  ciotx — Update Script
#
#  Pulls latest code, rebuilds CLI binaries for all platforms,
#  regenerates install.sh, rebuilds the server Docker image,
#  and restarts all services.
#
#  Usage (run on the VPS after every code push):
#    sudo ./scripts/update.sh
# =======================================================================

set -euo pipefail

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${BLUE}[*]${NC} $1"; }
success() { echo -e "${GREEN}[+]${NC} $1"; }
warn()    { echo -e "${YELLOW}[!]${NC} $1"; }
error()   { echo -e "${RED}[!] ERROR:${NC} $1" >&2; exit 1; }

[[ "$EUID" -ne 0 ]] && error "Run as root: sudo ./scripts/update.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

echo ""
echo -e "${BOLD}${BLUE}══════════════════════════════════════════════${NC}"
echo -e "${BOLD}  ciotx — Update${NC}"
echo -e "${BOLD}${BLUE}══════════════════════════════════════════════${NC}"
echo ""

# ── Load .env ────────────────────────────────────────────────────────
[[ ! -f .env ]] && error ".env not found."
set -a
source <(grep -v '^#' .env | grep -v '^$')
set +a
[[ -z "${DOMAIN_NAME:-}" ]] && error "DOMAIN_NAME not set in .env"

# ── Step 1: Pull latest code ─────────────────────────────────────────
info "Pulling latest code..."
# Stash any local edits (e.g. accidental changes to deploy.sh) so pull never blocks.
# .env is in .gitignore so it is never stashed or overwritten.
git stash --quiet 2>/dev/null || true
git pull
# Ensure this script is executable after pull (git may not preserve +x on some systems)
chmod +x scripts/update.sh scripts/deploy.sh
success "Code updated to $(git rev-parse --short HEAD)."

# ── Step 2: Ensure Go is available ───────────────────────────────────
if ! command -v go &>/dev/null; then
    info "Go not found — installing Go 1.27..."
    GO_TAR="go1.27.0.linux-amd64.tar.gz"
    curl -fsSL "https://dl.google.com/go/${GO_TAR}" -o "/tmp/${GO_TAR}"
    rm -rf /usr/local/go
    tar -C /usr/local -xzf "/tmp/${GO_TAR}"
    rm "/tmp/${GO_TAR}"
    success "Go installed."
fi
export PATH="/usr/local/go/bin:$PATH"
success "Go $(go version | awk '{print $3}') ready."

# ── Step 3: Build CLI binaries for all platforms ─────────────────────
info "Building CLI binaries..."
mkdir -p dist data/static/releases

VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "1.0.0")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
LDFLAGS="-s -w \
  -X main.APIEndpoint=https://${DOMAIN_NAME} \
  -X main.WebsiteURL=https://${DOMAIN_NAME} \
  -X main.Version=${VERSION} \
  -X main.Commit=${COMMIT} \
  -X main.BuildDate=${BUILD_DATE}"

info "  Version = ${VERSION} (${COMMIT})"
(
  cd cli
  CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o "../dist/ciotx-linux-amd64"       ./cmd/ciotx && info "  [+] linux/amd64"
  CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o "../dist/ciotx-linux-arm64"       ./cmd/ciotx && info "  [+] linux/arm64"
  CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o "../dist/ciotx-darwin-amd64"      ./cmd/ciotx && info "  [+] darwin/amd64"
  CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o "../dist/ciotx-darwin-arm64"      ./cmd/ciotx && info "  [+] darwin/arm64 (Apple Silicon)"
  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o "../dist/ciotx-windows-amd64.exe" ./cmd/ciotx && info "  [+] windows/amd64"
)
cp dist/ciotx-* data/static/releases/
success "CLI binaries built and live in data/static/releases/."

# ── Step 4: Regenerate install.sh with new version ───────────────────
info "Regenerating install.sh (version: ${VERSION})..."
cat > ./scripts/install.sh << INSTALL_SCRIPT
#!/bin/sh
# ciotx installer — generated by update.sh for ${DOMAIN_NAME}
# curl -fsSL https://${DOMAIN_NAME}/install.sh | sh

set -e

CIOTX_DOMAIN="https://${DOMAIN_NAME}"
CIOTX_VERSION="${VERSION}"
INSTALL_DIR="/usr/local/bin"

echo ""
echo "  ciotx — Security Auditor v\${CIOTX_VERSION}"
echo "  Installing from \${CIOTX_DOMAIN}..."
echo ""

OS="\$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="\$(uname -m)"

case "\${ARCH}" in
  x86_64)        ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *) echo "[!] Unsupported architecture: \${ARCH}"; exit 1 ;;
esac

case "\${OS}" in
  linux|darwin) ;;
  *) echo "[!] Unsupported OS: \${OS}. Windows: download from \${CIOTX_DOMAIN}/releases/"; exit 1 ;;
esac

BINARY="ciotx-\${OS}-\${ARCH}"
URL="\${CIOTX_DOMAIN}/releases/\${BINARY}"

echo "  Platform : \${OS}/\${ARCH}"
echo "  Downloading \${BINARY}..."

TMP="\$(mktemp -d)"
trap 'rm -rf \$TMP' EXIT

curl -fsSL "\${URL}" -o "\${TMP}/ciotx" || {
  echo "[!] Download failed. Check: \${URL}"
  exit 1
}

chmod +x "\${TMP}/ciotx"

if [ -w "\${INSTALL_DIR}" ]; then
  mv "\${TMP}/ciotx" "\${INSTALL_DIR}/ciotx"
else
  sudo mv "\${TMP}/ciotx" "\${INSTALL_DIR}/ciotx"
fi

echo ""
echo "  [+] ciotx v\${CIOTX_VERSION} installed!"
echo ""
echo "  Next steps:"
echo "    ciotx auth login"
echo "    ciotx scan ."
echo ""
echo "  Get your license key at \${CIOTX_DOMAIN}"
echo ""
INSTALL_SCRIPT

chmod +x ./scripts/install.sh
success "install.sh regenerated."

# ── Step 5: Rebuild server image and restart all services ─────────────
info "Rebuilding server and restarting services..."
docker compose up --build -d
success "Services restarted."

# ── Step 6: Health check ─────────────────────────────────────────────
info "Waiting for API to be healthy..."
sleep 10
for attempt in $(seq 1 12); do
    HTTP_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://${DOMAIN_NAME}/health" 2>/dev/null || echo "000")
    if [[ "$HTTP_CODE" == "200" ]]; then
        success "Health check passed — API is live."
        break
    fi
    warn "Attempt ${attempt}/12 — HTTP ${HTTP_CODE}, retrying in 5s..."
    sleep 5
    if [[ "$attempt" -eq 12 ]]; then
        echo ""
        docker compose logs --tail=30 api
        error "API did not come up healthy. Check logs above."
    fi
done

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║         ciotx Updated Successfully!          ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Version     ${NC}: ${VERSION} (${COMMIT})"
echo -e "  ${BOLD}API         ${NC}: https://${DOMAIN_NAME}"
echo -e "  ${BOLD}Client update command:${NC}"
echo -e "  ${BLUE}curl -fsSL https://${DOMAIN_NAME}/install.sh | sh${NC}"
echo ""
